//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomnaya
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Student_CountsEntities : DbContext
    {
        private static Student_CountsEntities _instance;
        public Student_CountsEntities()
            : base("name=Student_CountsEntities")
        {
        }
        public static Student_CountsEntities GetContext()
        {
            if (_instance == null)
                _instance = new Student_CountsEntities();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Father> Fathers { get; set; }
        public virtual DbSet<Groupp> Groupps { get; set; }
        public virtual DbSet<Mother> Mothers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
