//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplomnaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int Group_id { get; set; }
        public System.DateTime Birth { get; set; }
        public string Status { get; set; }
        public string Residence { get; set; }
        public int Passport { get; set; }
        public string Telephone { get; set; }
        public string Adress { get; set; }
        public int Father { get; set; }
        public int Mother { get; set; }
    
        public virtual Father Father1 { get; set; }
        public virtual Groupp Groupp { get; set; }
        public virtual Mother Mother1 { get; set; }
    }
}
